main/urls.py
from django.urls import path
from main.endpoints.views import *
from main.endpoints.auth_views import *
from main.endpoints.pass_views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('manicure/', ManicureView.as_view(), name='manicure'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('about/', AboutView.as_view(), name='about'),

    path('times_result/', times_result, name='times_result'),
    path('times_result_admin/', times_result_admin, name='times_result_admin'),
    path('select_service/<int:pk>/', SelectServiceView.as_view(), name='select_service'),
    path('confirm_manicure/<int:pk>/', confirm_manicure, name='confirm_manicure'),
    path('edit_service/<int:pk>/', EditServiceView.as_view(), name='edit_service'),
    path('add_manicure/<str:date>/', AddManicureView.as_view(), name='add_manicure'),
    path('delete_manicure/<int:pk>/', DeleteManicureView.as_view(), name='delete_manicure'),
    path('edit_manicure/<int:pk>/', EditManicureView.as_view(), name='edit_manicure'),
    path('cancel_manicure/<int:pk>/', cancel_manicure, name='cancel_manicure'),

    path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('password_change_done/', PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', PasswordReset.as_view(), name='password_reset'),
    path('password_reset_done/', PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<slug:uidb64>/<slug:token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),

    path('account/login/', UserLogin.as_view(), name='user_login'),
    path('account/signup/', UserRegister.as_view(), name='user_register'),
    path('user_detail/<slug:slug>/', UserDetailView.as_view(), name='user_detail'),
    path('user_history/<slug:slug>/', UserHistoryView.as_view(), name='user_history'),
    path('user_update/<slug:slug>/', UserUpdateView.as_view(), name='user_update'),
    path('user_logout/', user_logout, name='user_logout'),
]

nails/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from nails import settings
from django.conf.urls.static import static
from django.views.static import serve as mediaserve
from main.endpoints.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:

    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # подключаем ссылку на статические медиа файлы только в режиме отладки
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

handler404 = pageNotFound       # вызов функции обработчика страница не найдена

main/models.py
from django.contrib.auth.models import User, AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from slugify import slugify
from django.urls import reverse

from .managers import CustomUserManager


def upload_photo_autor(instance, filename):
    return 'photos/users/{0}/{1}'.format(instance.slug, filename)


class CustomUser(AbstractUser):

    email = models.EmailField(_("email address"), unique=True)

    slug = models.SlugField(verbose_name='Ваш ID', unique=True, db_index=True, null=True)
    photo = models.ImageField(upload_to=upload_photo_autor, verbose_name='Фото', null=True, blank=True)
    instagram = models.CharField(max_length=50, verbose_name='Инстаграм', null=True, blank=True)
    mobile = models.CharField(max_length=20, verbose_name='Телефон', null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.email)
        self.username = self.email
        return super(CustomUser, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('user_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.email


class Manicure(models.Model):
    title = models.CharField(max_length=20, verbose_name='Название', blank=True, null=True, validators=[RegexValidator(regex=r'^([1-31].)', message='такое время существует')], unique=True)
    time = models.CharField(max_length=5, verbose_name='Время', validators=[RegexValidator(regex=r'^(([0,1][0-9])|(2[0-2])):(([0-5][0-9])|(00))$', message='Неверный формат времени!')])
    client = models.ForeignKey('CustomUser', on_delete=models.SET_DEFAULT, verbose_name='Клиент', default=None, blank=True, null=True)
    service = models.ForeignKey('Service', on_delete=models.DO_NOTHING, verbose_name='Доступные услуги', default=None, blank=True, null=True)
    date = models.DateField(verbose_name='Дата', default=None)
    is_active = models.BooleanField(verbose_name='Опубликовать', default=True)

    # def save(self, *args, **kwargs):
    #     day = str(self.date)
    #     day = day.split('-')
    #     time_out = str(self.time)
    #     time_out = time_out.split(':')
    #     self.title = day[2] + '.' + day[1] + '.' + day[0][2:] + ' ' + str(self.time) + '-' + str(int(time_out[0])+2) + ':' + time_out[1]        # 21.08.24 19:00-21:00
    #
    #     return super(Manicure, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи на ногти'
        ordering = ['-date', 'title']


class Service(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название', validators=[RegexValidator(regex=r'$', message='Неверный формат поля!')])
    price = models.IntegerField(default=0, verbose_name='Цена в рублях')

    def save(self, *args, **kwargs):
        self.title = str(self.title) + ' = ' + str(self.price) + 'р.'
        return super(Service, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Мои услуги'
        ordering = ['id']

main/endpoints/views.py
import datetime

from allauth.account.models import EmailAddress
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseNotFound, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView, CreateView, DeleteView

from main.forms import *
from main.models import *


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Page not found</h1>')


class HomeView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['title'] = 'Главная'
        return context


class ManicureView(TemplateView):
    template_name = 'main/manicure.html'

    def get_context_data(self, **kwargs):
        context = super(ManicureView, self).get_context_data(**kwargs)
        today = datetime.date.today()
        yesterday = today - datetime.timedelta(days=1)
        all_posts = Manicure.objects.filter(date__gt=yesterday, client=None, is_active=True)            # поиск всех свободных дней

        free_dates = []
        for el in all_posts:
            free_dates.append(str(el.date))
        free_dates.append(str(today))

        if not self.request.user.is_authenticated:                                                      # Если пользователь не авторизован
            dates = free_dates
        else:                                                                                           # Если пользователь авторизован
            n = 1                                                                                       # сколько дней за и после неактивны со дня записи
            busy_posts = Manicure.objects.filter(date__gt=yesterday, client=self.request.user)          # поиск всех предстоящих записей для пользователя

            busy_dates = []
            if busy_posts:
                for el in busy_posts:
                    for i in range(n+1):
                        busy_dates.append(str(el.date - datetime.timedelta(days=i)))
                        busy_dates.append(str(el.date + datetime.timedelta(days=i)))
            dates = set(free_dates) - set(busy_dates)
            dates = list(dates)

        context['title'] = 'Запись на маникюр'
        context['body_title'] = 'Запись на маникюр'
        context['dates'] = dates
        return context


class AddManicureView(CreateView):
    form_class = ManicureForm
    template_name = 'main/edit_manicure.html'
    success_url = reverse_lazy('manicure')

    def form_valid(self, form):
        day = str(form.cleaned_data.get('date'))
        day = day.split('-')
        time_out = str(form.cleaned_data.get('time'))
        time_out = time_out.split(':')
        form.instance.title = day[2] + '.' + day[1] + '.' + day[0][2:] + ' ' + str(form.cleaned_data.get('time')) + '-' + str(int(time_out[0])+2) + ':' + time_out[1]
        try:
            return super().form_valid(form)
        except:
            return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(AddManicureView, self).get_context_data(**kwargs)
        context['form'] = ManicureForm(initial={'date': self.kwargs['date']})
        return context


class DeleteManicureView(DeleteView):
    model = Manicure
    pk_url_kwarg = 'pk'
    context_object_name = 'el'
    success_url = reverse_lazy('manicure')
    template_name = 'main/manicure_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super(DeleteManicureView, self).get_context_data(**kwargs)
        context['title'] = 'Удаление записи'
        context['body_title'] = 'Подтвердите удаление'
        return context


def times_result(request):
    today = datetime.datetime.today().date()
    if request.method == 'GET':
        date_str = request.GET.get('datepicker_value')
        date = datetime.datetime.strptime(date_str, '%Y-%m-%d').date()
        if date < today:
            date = None
            return render(request, 'main/times_result.html', context={'date': date})

    times = Manicure.objects.filter(date=date, client=None, is_active=True)
    context = {
        'times': times,
        'date': date,
    }
    return render(request, 'main/times_result.html', context)


def times_result_admin(request):
    today = datetime.datetime.today().date()
    if request.method == 'GET':
        date_str = request.GET.get('datepicker_value_admin')
        date = datetime.datetime.strptime(date_str, '%Y-%m-%d').date()
        if date < today:
            date = None
            return render(request, 'main/times_result.html', context={'date': date})

    times = Manicure.objects.filter(date=date, client=None, is_active=True)
    context = {
        'times': times,
        'date': date,
    }
    return render(request, 'main/times_result_admin.html', context)


class SelectServiceView(LoginRequiredMixin, TemplateView):
    template_name = 'main/select_service.html'
    login_url = reverse_lazy('user_login')

    def get_context_data(self, **kwargs):
        context = super(SelectServiceView, self).get_context_data(**kwargs)
        post = Manicure.objects.get(pk=self.kwargs['pk'])

        today = datetime.date.today()
        yesterday = today - datetime.timedelta(days=1)

        all_posts = Manicure.objects.filter(date__gt=yesterday, client=None, is_active=True)        # поиск всех свободных дней
        free_dates = []
        for el in all_posts:
            free_dates.append(str(el.date))
        free_dates.append(str(today))

        n = 1                                                                                       # сколько дней за и после неактивны со дня записи
        busy_posts = Manicure.objects.filter(date__gt=yesterday, client=self.request.user)          # поиск всех предстоящих записей для пользователя
        busy_dates = []
        if busy_posts:
            for el in busy_posts:
                for i in range(n+1):
                    busy_dates.append(str(el.date - datetime.timedelta(days=i)))
                    busy_dates.append(str(el.date + datetime.timedelta(days=i)))
        dates = set(free_dates) - set(busy_dates)
        dates = list(dates)

        if str(post.date) in dates:
            context['title'] = 'Выберите услугу'
            context['body_title'] = 'Выберите услугу'
            context['form'] = ServiceForm(initial={'service': post.service})
            context['pk'] = self.kwargs['pk']
        else:
            context['error'] = 'Ошибка'
        return context


def confirm_manicure(request, pk):
    post = Manicure.objects.get(pk=pk)

    post.client = request.user
    post.service = Service.objects.get(pk=request.POST['service'])
    post.is_active = False
    post.save()
    return redirect('user_history', slug=request.user.slug)


class EditServiceView(LoginRequiredMixin, UpdateView):
    template_name = 'main/edit_manicure.html'
    pk_url_kwarg = 'pk'
    model = Manicure
    form_class = ServiceForm

    login_url = reverse_lazy('user_login')

    def get_success_url(self):
        return reverse('user_history', kwargs={'slug': self.request.user.slug})

    def get_context_data(self, **kwargs):
        context = super(EditServiceView, self).get_context_data(**kwargs)
        post = Manicure.objects.get(pk=self.kwargs['pk'])

        if post.client == self.request.user and post.date >= datetime.date.today():
            context['title'] = 'Выберите услугу'
            context['body_title'] = 'Выберите услугу'
        else:
            context['error'] = 'Ошибка'
        return context


class EditManicureView(LoginRequiredMixin, UpdateView):
    template_name = 'main/edit_manicure.html'
    pk_url_kwarg = 'pk'
    model = Manicure
    form_class = ManicureForm
    success_url = reverse_lazy('manicure')

    login_url = reverse_lazy('user_login')

    def get_context_data(self, **kwargs):
        context = super(EditManicureView, self).get_context_data(**kwargs)
        if self.request.user.is_staff:
            context['title'] = 'Изменить данные'
            context['body_title'] = 'Изменить данные'
        else:
            context['error'] = 'Ошибка'
        return context


def cancel_manicure(request, pk):
    post = Manicure.objects.get(pk=pk)
    if (request.user.is_authenticated and request.user == post.client) or request.user.is_staff:
        post.is_active = True
        post.service = None
        post.client = None
        post.save()

    return redirect('user_history', slug=request.user.slug)


class AboutView(TemplateView):
    template_name = 'main/about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['title'] = 'О нас'
        context['body_title'] = 'О нас'
        return context


class ContactsView(TemplateView):
    template_name = 'main/contacts.html'

    def get_context_data(self, **kwargs):
        context = super(ContactsView, self).get_context_data(**kwargs)
        context['title'] = 'Контакты'
        context['body_title'] = 'Контакты'
        return context

main/views.py
from django.http import HttpResponseNotFound, HttpResponse
from django.shortcuts import render

from .models import *


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Page not found</h1>')


def home(request):
    context = {
        'title': 'Главная страница'
    }
    return render(request, 'main/index.html', context)


def about(request):
    return HttpResponse("About page")


def contacts(request):
    return HttpResponse("Contacts page")


def authorization(request):
    return HttpResponse("Authorization page")


def user_detail(request, slug):
    email = CustomUser.objects.get(slug=slug).email
    return HttpResponse(f"User detail page {email}")

main/templates/main/about.html
{% extends 'main/base.html' %}


{% block body %}

    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm" style="text-align: center;">
            <h4>About</h4>
        </div>
        <div class="col-sm"></div>
    </div>

{% endblock %}

main/templates/main/authorization.html
{% extends 'main/base.html' %}
{% load static main_tags %}


{% block body %}

<style>
    .login-form {
        padding: 10px;
    }
    .border-form {
        padding: 10px;
        border-radius: 12px; /* Радиус скругления */
        border: 2px solid grey; /* Параметры рамки */
        box-shadow: 0 0 5px #666; /* Параметры тени */
    }
</style>

    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm login-form">
            <div class="border-form">
                <form method="post">
                    {% csrf_token %}
                    {% for el in form %}
                    <p><label for="{{el.id_for_label}}">{{ el.label }}:</label> {{ el }}</p>
                    <div class="form-error"> {{ el.errors }}</div>   <!-- Выдается ошибка по отдельному полю формы -->
                    {% endfor %}
                    {{ form.non_field_errors }}
                    <button class="btn btn-success" type="submit">Войти</button>
                </form><br>
            </div>
            <br>
            &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'home' %}">Не зарегистрированы?</a><br>
            &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'home' %}">Забыли пароль?</a><br><br>
            <br>
        </div>
        <div class="col-sm"></div>
    </div>

{% endblock %}

main/templates/main/contacts.html
{% extends 'main/base.html' %}


{% block body %}

    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm" style="text-align: center;">
            <h4>Contacts</h4>
        </div>
        <div class="col-sm"></div>
    </div>

{% endblock %}

main/templates/main/manicure_confirm_delete.html
{% extends 'main/base.html' %}


{% block body %}


    <div class="row" style="text-align: center; margin: 0 10%;">
        <div class="col-sm"></div>
        <div class="col-sm">

            <form method="post">
                {% csrf_token %}
                <p>вы уверены что хотите удалить запись на {{ el.title }}?</p>
                <button class="btn btn-primary btn-sm" type="submit">Подтвердить</button>
                <a class="btn btn-danger btn-sm" href="{% url 'manicure' %}">Отменить</a>
            </form>

        </div>
        <div class="col-sm"></div>
    </div>


{% endblock %}

main/templates/main/select_service.html
{% extends 'main/base.html' %}


{% block body %}

    {% if not error %}
        <div style="text-align: center; margin: 0 10%;">

            <form method="post" action="{% url 'confirm_manicure' pk %}">

                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary btn-sm" type="submit">Подтвердить</button>

            </form>
        </div>
    {% else %}
        <div style="text-align: center;">
            <br><br>
            <strong>Ошибка доступа</strong>
        </div>
    {% endif %}

{% endblock %}

main/templates/main/times_result.html
{% if date %}

    {% if times %}

        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">

                <div class="alert alert-secondary" style="margin-bottom: 50px;" role="alert">
                    <ol>
                        {% for el in times %}
                            {% if request.user.is_staff %}
                                <li style="margin: 10px 0;"><strong><a href="{% url 'edit_manicure' el.pk %}">{{ el.title }}</a></strong>&nbsp;&nbsp;
                                    <a class="btn btn-primary btn-sm" href="{% url 'select_service' el.pk %}">выбор</a>
                                    <a class="btn btn-danger btn-sm" href="{% url 'delete_manicure' el.pk %}">удалить</a>
                                </li>
                            {% else %}
                                <li style="margin: 10px 0;"><strong>{{ el.title }}</strong>&nbsp;&nbsp;
                                    <a class="btn btn-primary btn-sm" href="{% url 'select_service' el.pk %}">выбор</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if request.user.is_staff %}
                            <a href="{% url 'add_manicure' date %}" class="btn btn-primary btn-sm">добавить запись</a>
                        {% endif %}
                    </ol>
                </div>

            </div>
            <div class="col-sm"></div>
        </div>

    {% else %}

        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">

                <div class="alert alert-secondary" role="alert">
                    <p style="margin: 10px 0;"><strong>На {{ date|date:"d.m.y" }} нет записей</strong></p>
                </div>

            </div>
            <div class="col-sm"></div>
        </div>

    {% endif %}

{% else %}

    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm">

            <div class="alert alert-secondary" role="alert">
                <p style="margin: 10px 0;"><strong>Выберите доступный день!!!</strong></p>
            </div>

        </div>
        <div class="col-sm"></div>
    </div>

{% endif %}

main/templates/main/times_result_admin.html
{% if date %}

    {% if times %}

        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">

                <div class="alert alert-secondary" style="margin-bottom: 50px;" role="alert">
                    <ol>
                        {% for el in times %}
                            <li style="margin: 10px 0;"><strong><a href="{% url 'edit_manicure' el.pk %}">{{ el.title }}</a></strong>&nbsp;&nbsp;
                                <a class="btn btn-primary btn-sm" href="{% url 'select_service' el.pk %}">выбор</a>
                                <a class="btn btn-danger btn-sm" href="{% url 'delete_manicure' el.pk %}">удалить</a>
                            </li>
                        {% endfor %}
                    </ol>
                    <a href="{% url 'add_manicure' date %}" class="btn btn-primary btn-sm">добавить запись</a>
                </div>

            </div>
            <div class="col-sm"></div>
        </div>

    {% else %}

        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">

                <div class="alert alert-secondary" role="alert">
                    <p style="margin: 10px 0;"><strong>На {{ date|date:"d.m.y" }} нет записей</strong></p>
                    <a href="{% url 'add_manicure' date %}" class="btn btn-primary btn-sm">добавить запись</a>
                </div>

            </div>
            <div class="col-sm"></div>
        </div>

    {% endif %}

{% else %}

    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm">

            <div class="alert alert-secondary" role="alert">
                <p style="margin: 10px 0;"><strong>Выберите доступный день!!!</strong></p>
            </div>

        </div>
        <div class="col-sm"></div>
    </div>

{% endif %}

main/templates/main/user_history.html
{% extends 'main/base.html' %}

{% block body %}

    {% if not error %}
        <br>
        {% if posts %}
            {% for el in posts %}
                <div class="alert alert-secondary" role="alert" style="margin: 10px 5%; padding: 20px 20px 50px 20px;">

                    <strong>{{ el.title }} | {{ el.service }} | {{ el.date|date:"d.m.y" }}</strong><br><br>
                    <a class="btn btn-danger btn-sm" style="float: right;" href="{% url 'cancel_manicure' el.pk %}">Отказаться</a>
                    <a class="btn btn-primary btn-sm" style="float: right; margin-right: 10px;" href="{% url 'edit_service' el.pk %}">Изменить</a>

                </div>
            {% endfor %}
        {% else %}
            <div style="text-align: center;">
                <strong>У вас нет активных записей</strong>
            </div>
        {% endif %}

    {% else %}
        <style>
            .error-center {
                text-align: center;
                color: red;
            }
        </style>
        <div class="error-center">
            <h2>{{ error }}</h2>
        </div>
    {% endif %}

{% endblock %}

main/templates/main/user_login.html
{% extends 'main/base.html' %}
{% load static main_tags %}


{% block body %}

<style>
    .login-form {
        padding: 10px;
    }
    .border-form {
        padding: 10px;
        border-radius: 12px; /* Радиус скругления */
        border: 2px solid grey; /* Параметры рамки */
        box-shadow: 0 0 5px #666; /* Параметры тени */
    }
</style>

    <div class="row" style="margin: 0;">
        <div class="col-sm"></div>
        <div class="col-sm login-form">
            <div class="border-form">
                <form method="post">
                    {% csrf_token %}
                    {% for el in form %}
                    <p><label for="{{el.id_for_label}}">{{ el.label }}:</label> {{ el }}</p>
                    <div class="form-error"> {{ el.errors }}</div>   <!-- Выдается ошибка по отдельному полю формы -->
                    {% endfor %}
                    <div style="color: red;">{{ form.non_field_errors }}</div>
                    <button class="btn btn-success" type="submit">Войти</button>
                </form><br>
            </div>
            <br>
            &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'user_register' %}">Не зарегистрированы?</a><br>
            &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'password_reset' %}">Забыли пароль?</a><br><br>
            <br>
        </div>
        <div class="col-sm"></div>
    </div>

{% endblock %}

main/templates/main/user_register.html
{% extends 'main/base.html' %}

{% block body %}

    {% if not error %}

        <div class="row" style="margin: 0;">
            <div class="col-sm"></div>
            <div class="col-sm">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for el in form %}
                        <p><label for="{{el.id_for_label}}">{{ el.label }}:</label> {{ el }}</p>
                        <div class="form-error"> {{ el.errors }}</div>   <!-- Выдается ошибка по отдельному полю формы -->
                    {% endfor %}<br>
                    <button class="btn btn-success" type="submit">Подтвердить</button>
                </form><br><br>

<!--                <script type="text/javascript">-->
<!--                        $("#tel").mask("+375 (99) 999-99-99",{placeholder:"x"});-->
<!--                </script>-->

                <!-- подключение скриптов для автозаполнения поля slug -->
<!--                <script id="django-admin-form-add-constants"-->
<!--                    src="/static/admin/js/change_form.js"-->
<!--                        data-model-name="customuser"-->
<!--                    async>-->
<!--                </script>-->
<!--                <script id="django-admin-prepopulated-fields-constants"-->
<!--                        src="/static/admin/js/prepopulate_init.js"-->
<!--                        data-prepopulated-fields="[{&quot;id&quot;: &quot;#id_slug&quot;, &quot;username&quot;: &quot;slug&quot;, &quot;dependency_ids&quot;: [&quot;#id_username&quot;], &quot;dependency_list&quot;: [&quot;username&quot;], &quot;maxLength&quot;: 50, &quot;allowUnicode&quot;: false}]">-->
<!--                </script>-->

            </div>
            <div class="col-sm"></div>
        </div>

    {% else %}
        <style>
            .error-center {
                text-align: center;
                color: red;
            }
        </style>
        <div class="error-center">
            <h5>{{ error }}</h5>
        </div>
    {% endif %}

{% endblock %}